---
- name: Download and install k3s
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -"
  ignore_errors: true

- name: Check install
  ansible.builtin.command: "k3s --version"
  register: k3s_version

- name: Print k3s version
  ansible.builtin.debug:
    msg: "{{ k3s_version.stdout }}"
  failed_when: k3s_version.rc != 0
